#7 - Allow businesses to add link to their profiles
2055Java-Nick/Rev-Connect-API pull request #15
Opened 2024-08-15 20:56 UTC by asndiallo

2024-08-22 19:50 UTC, themellowpea commented on .gitignore
untrack this file

2024-08-22 19:50 UTC, themellowpea commented on .project
remove this

2024-08-22 19:51 UTC, themellowpea commented on .vscode/launch.json
untrack this folder .vscode

2024-08-22 19:53 UTC, themellowpea requested changes
pull from `dev`, resolve merge conflicts. You will most likely have to refactor a few things.

2024-08-23 13:45 UTC, asndiallo commented on .gitignore
untrack gitignore ?

2024-09-03 17:18 UTC, closed without merging